#!groovy

// Generated by IBM TransformationAdvisor
// Wed Feb 27 07:33:55 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'sample'
    mvnCommands = '--version'
    test='false'
}